#!/bin/bash 

J_SERVER=jenkins.mv.cariden.com
J_PROJECT=CANARY
J_BASE_URL=http://$J_SERVER/job/CANARY/label=linux64/lastStableBuild/artifact

ROOT_DIR=/opt/cariden

die() {
    echo "### ERROR ### $*. Exiting."
    exit 1
}

log() {
    echo --- $*
}

# check if we have network connectivity and try to fix it if not
ping $J_SERVER -c 1 -w 1 &> /dev/null
pingable=$?;
if [[ $pingable != 0 && `grep jenkins /etc/hosts | wc -l` == 0 ]]; then
   log "Can't access $J_SERVER. Trying to add it to /etc/hosts..."
   sudo sh -c "echo 172.16.0.21   $J_SERVER >> /etc/hosts"
fi

# check connectivty again
ping $J_SERVER -c 1 -w 1 &>/dev/null || die "Can't reach $J_SERVER. Try to ping it."

# find latest build
loc=`curl -s http://$J_SERVER/job/\
$J_PROJECT/label=linux64/lastStableBuild/api/json?pretty=true |\
grep -o 'build.*Linux-x86_64.bin'` || die "Can't retrieve the latest build."

LATEST_BUILD=`echo $loc | grep -o 'Cariden.*'`

log Latest successful build: $LATEST_BUILD.

# check if the file already exists
if [[ -f /tmp/$LATEST_BUILD ]]; then 
    log Using existing file /tmp/$LATEST_BUILD.
else
    log Downloading file...
    curl -o /tmp/$LATEST_BUILD -O $J_BASE_URL/$loc || die Failed to download to MATE package.
fi


# check if cariden user exits or create it
if [[ `cat /etc/passwd | grep cariden | wc -l` == 0 ]]; then
    log Creating cariden user
    sudo /usr/sbin/useradd --home-dir $ROOT_DIR --create-home cariden || die Failed to create user cariden.
    sudo chmod 755 $ROOT_DIR || die Failed to set permissions on $ROOT_DIR
else
    log Using existing cariden user.
fi

# check if $ROOT_DIR exits or create it
if [[ ! -d $ROOT_DIR ]]; then
    log Creating $ROOT_DIR...
    sudo mkdir -p $ROOT_DIR || die Failed to create $ROOT_DIR
    sudo chown cariden:cariden $ROOT_DIR || die to change ownership of $ROOT_DIR
fi

# shutdown tomcat if needed
if [[ "`sudo -u cariden -s $ROOT_DIR/software/mate/current/bin/embedded_web_server -action status 2>&1 | grep -o "The server is running" | wc -l`" == 1 ]]; then
    log shutting down tomcat
    sudo -u cariden -s $ROOT_DIR/software/mate/current/bin/embedded_web_server -action stop || die Failed to shut down tomcat.
fi

# Installing...
log Installing /tmp/$LATEST_BUILD...

chmod +x /tmp/$LATEST_BUILD || die Failed to add execution permissions to /tmp/$LATEST_BUILD.
sudo -u cariden sh -c "/tmp/$LATEST_BUILD -d $ROOT_DIR" || die Failed to install. 

log Restarting tomcat
sudo -u cariden -s $ROOT_DIR/software/mate/current/bin/embedded_web_server -action start || die Failed to start tomcat
sleep 5
sudo -u cariden -s $ROOT_DIR/software/mate/current/bin/embedded_web_server -action status || die Failed to retrieve tomcat status

log Adding automatic server start @reboot
sudo -u cariden sh -c "(crontab -l &> /dev/null ; echo \"@reboot $ROOT_DIR/software/mate/current/bin/embedded_web_server -action start\") | uniq - | crontab -" || die Failed to add to crontab

log Done. You may to deactivate your firewall: sudo service iptables stop; sudo chkconfig iptables off
